// import Header from "@/components/Header/Header";
import Header from "@/components/Header/Header"
import 'flag-icons/css/flag-icons.min.css';
import "./globals.css";
import { Footer } from "@/components/Footer";
import { Toaster } from "sonner";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <Header />
        {children}
        <Footer/>
        <Toaster richColors position="top-right" />
      </body>
    </html>
  );
}
