import Header from "@/components/Header/Header";
import 'flag-icons/css/flag-icons.min.css';
import "./globals.css";
import { Footer } from "@/components/Footer";
import { LanguageProvider } from "./context/LanguageContext";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        {/* WRAP EVERYTHING WITH LANGUAGE PROVIDER */}
        <LanguageProvider>
          <Header />
          {children}
          <Footer/>
        </LanguageProvider>
      </body>
    </html>
  );
}